# This is a basic workflow to help you get started with Actions

name: Issue data pusher

# Controls when the workflow will run
  # Triggers the workflow when issue is opened
on:
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Update data.json
        run: echo "`jq '.data[0].content="github.event.issue.title"' data.json`" > data.json
      - name: read data.json
        run: cat data.json
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          message: 'updating data'
          add: "data.json"
